### ISSUE TITLE
Docker Compose Not Working on Fresh Clone

### ISSUE THREAD

**Issue by PaulStegler** [theSherwood/PDQ-coding-challenge#1]
# Steps to Reproduce Issue

- clone the project
- have docker installed
- have node v10.15.3 installed
- have npm v6.4.1 installed
- navigate to cloned project root in terminal
- run ```docker-compose up```
- observe the following error

> Starting server ... done
Starting client ... done
Attaching to server, client
server    |
server    | > app@1.0.0 dev /server
server    | > nodemon server.js
server    |
server    | sh: nodemon: not found
server    | npm ERR! file sh
server    | npm ERR! code ELIFECYCLE
server    | npm ERR! errno ENOENT
server    | npm ERR! syscall spawn
server    | npm ERR! app@1.0.0 dev: `nodemon server.js`
server    | npm ERR! spawn ENOENT
server    | npm ERR!
server    | npm ERR! Failed at the app@1.0.0 dev script.
server    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
server    | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
server    |
server    | npm ERR! A complete log of this run can be found in:
server    | npm ERR!     /root/.npm/_logs/2019-08-06T19_05_16_787Z-debug.log
client    |
client    | > client@0.1.0 start /client
client    | > react-scripts start
client    |
client    | sh: react-scripts: not found
client    | npm ERR! file sh
client    | npm ERR! code ELIFECYCLE
client    | npm ERR! errno ENOENT
client    | npm ERR! syscall spawn
client    | npm ERR! client@0.1.0 start: `react-scripts start`
client    | npm ERR! spawn ENOENT
client    | npm ERR!
client    | npm ERR! Failed at the client@0.1.0 start script.
client    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
client    | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
client    |
client    | npm ERR! A complete log of this run can be found in:
client    | npm ERR!     /root/.npm/_logs/2019-08-06T19_05_16_809Z-debug.log
server exited with code 1
client exited with code 1

# Change Request
Hi @theSherwood, this is Paul from PDQ.com. I couldn't get the docker compose working. Can you fix the project so the docker compose works out of the box on a fresh clone?

**Comment by theSherwood** [comment]
Hi Paul,

Sorry about that. I've pushed the fix to the repo and tested it. It should
all be working now.

Best wishes,

Adam

**Comment by FarrahStark** [comment]
Hi Adam,
Thanks for the quick turnaround on fixing this! I was able to run it the first time no problem with your update. Good work!
Regards,
Paul

**Comment by theSherwood** [comment]
Excellent! Closing the issue then...
